{
    "name": "Project Workflow (DEC)",
    "version": "14.0.1.0.0",
    "author": "DEC",
    "website": "https://www.decgroupe.com",
    "depends": [
        "hr_timesheet",
        "sale_timesheet",
        "sale_timesheet_line_exclude",
        # 'sale_timesheet_task_exclude', [MIG] 14.0: Not needed anymore acoording to https://github.com/OCA/timesheet/pull/440#issuecomment-1235611830
        "project_list",
        "project_action_view",
        "project_activity",
        "project_category",
        "project_identification",
        "project_timesheet_time_control",
        "project_task_default_stage",
        "web_kanban_draggable",
        "web",
        "mail_activity_workflow_dec",
    ],
    "data": [
        "views/assets.xml",
        "views/project_project.xml",
        "views/project_task.xml",
        "data/project_type.xml",
        "data/project.xml",
        "data/project_task_type.xml",
        "data/project_task.xml",
        "data/project_tags.xml",
    ],
    "demo": [
        "demo/product_product.xml",
        "demo/res_users.xml",
    ],
    "installable": True,
}
